import argparse
from pathlib import Path
import subprocess
import sys
from .profile import add_profile_entry

# laab-process trace_dir/ 
#           --name dense/gemm/cpu/mt/ 
# 			--system "kebnekaise:cpu_sky"
# 			--lib openblas  
# 			--version  "5.1"
# 			--toolchain gompi2025a 
# 			--cb_id $jube_wp_id
# 			--np 8
# 			--work_dist "-N 2 --ntasks-per-node 4 -c 72"
#           --pinning="--cpu_bind=cores --distribution=block:block" 
#            --profile_dir=../
   
def laab_process() -> None:
    parser = argparse.ArgumentParser(description="Prepare profiles from LAAB traces")
    parser.add_argument("trace_dir", help="Directory containing the trace files generated by LAAB")
    parser.add_argument("--profile_dir", required=True, help="Directory to store the profiles")
    parser.add_argument("--name", required=True, help="Name of the experiment")
    parser.add_argument("--system", required=True, help="System name to use for the experiment")
    parser.add_argument("--lib", required=True, help="Library name to use for the experiment")
    parser.add_argument("--version", required=True, help="Library version to use for the experiment")
    parser.add_argument("--toolchain", required=True, help="Toolchain name to use for the experiment")
    parser.add_argument("--np", required=True, type=int, help="Number of processes to use for the experiment")
    parser.add_argument("--work_dist", required=True, help="Work distribution to use for the experiment")
    parser.add_argument("--pinning", required=True, help="Pinning to use for the experiment")
    parser.add_argument("--cb_id", required=True, help="CB ID to use for the experiment")
    parser.add_argument("--options", default="base", help="Common workload options.")
    
    args = parser.parse_args()
    
    pinning = args.pinning
    if pinning:
        pinning = pinning.replace(" ", "+").replace("--", "")
    
    try:
        add_profile_entry(Path(args.trace_dir).expanduser(), 
                          Path(args.profile_dir).expanduser(),
                          args.name, 
                          args.system, 
                          args.lib, 
                          args.version, 
                          args.toolchain,  
                          args.np, 
                          args.work_dist,
                          pinning, 
                          args.cb_id,
                          args.options)
    except Exception as e:
        raise RuntimeError(f"Error processing traces: {e}") from e

def laab_delete_profile_entry() -> None:
    parser = argparse.ArgumentParser(description="Delete laab profile entry")
    parser.add_argument("profile_dir", help="Directory containing the profiles")
    parser.add_argument("--interface", required=True, help="Interface")
    parser.add_argument("--prob_size", required=True, help="Problem size")
    parser.add_argument("--prec", required=True, help="Precision")
    parser.add_argument("--np", required=True, type=int, help="Number of processes")
    parser.add_argument("--work_dist", required=True, help="Work distribution")
    parser.add_argument("--pinning", required=True, help="Pinning")
    parser.add_argument("--cb_id", required=True, help="CB ID")
    
    args = parser.parse_args()
    pinning = args.pinning
    if pinning:
        pinning = pinning.replace(" ", "+").replace("--", "")
        
    try:
        delete_profile_entry(args.interface, args.prob_size, args.prec, args.np, args.work_dist, pinning, args.cb_id, Path(args.profile_dir).expanduser())
    except Exception as e:
        print(f"Error deleting profile entry: {e}")


def laab_print_profile() -> None:
    parser = argparse.ArgumentParser(description="Print laab profile entry")
    parser.add_argument("profile_path", help="Path to the profile")
    args = parser.parse_args()
    
    from .profile import LAABProfile
    
    profile_path = Path(args.profile_path).expanduser()
    if not profile_path.exists():
        print(f"Profile not found at {profile_path}")
        return
    
    try:
        profile = LAABProfile.load(Path(args.profile_path).expanduser())
    except Exception as e:
        raise RuntimeError(f"Error loading profile: {e}") from e
    
    print("Step specs:")
    for key, value in profile.step_specs.items():
        print(f"  {key}: {value}")
    print("Run specs:")
    for key, value in profile.run_specs.items():
        print(f"  {key}: {value}")
    print("Host specs:")
    for key, value in profile.host_specs.items():
        print(f"  {key}: {value}")
        
    print()
    print("Execution times:")
    for key, value in profile.exec_times.items():
        print(f"  {key}: {value}")
    print("Compute performance:")
    for key, value in profile.compute_perfs.items():
        print(f"  {key}: {value}")
        
    print()
    print("Mean execution time:")
    for key, value in profile.mean_exec_time.items():
        print(f"  {key}: {value} s")
    print("Mean compute performance:")
    for key, value in profile.mean_compute_perf.items():
        print(f"  {key}: {value} GFLOPs/s")
    
    print()    
    print("CB ranks")
    for key, value in profile.cb_ranks.items():
        print(f"{key}:")
        print(f"ranks_m1: {value['ranks_m1']}")
        print(f"ranks_m2: {value['ranks_m2']}")
        print(f"ranks_m3: {value['ranks_m3']}")
        print(f"nranks: {value['nranks']}")
        print()
    
        

def laab_reprocess():
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <root_directory>")
        sys.exit(1)

    root_dir = Path(sys.argv[1]).resolve()

    if not root_dir.is_dir():
        print(f"Error: directory does not exist: {root_dir}")
        sys.exit(1)

    scripts = sorted(root_dir.rglob("laab_process.sh"))

    if not scripts:
        print("No laab_process.sh files found.")
        return

    for script in scripts:
        work_dir = script.parent

        print(f"\nRunning {script}")
        print(f"Working directory: {work_dir}")

        result = subprocess.run(
            ["bash", script.name],
            cwd=work_dir
        )

        if result.returncode != 0:
            print(
                f"Failed with return code {result.returncode}: "
                f"{script}"
            )
            
def laab_delete_profiles():
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <directory>")
        sys.exit(1)

    root_dir = Path(sys.argv[1]).resolve()

    if not root_dir.is_dir():
        print(f"Error: directory does not exist: {root_dir}")
        sys.exit(1)

    laab_count = 0
    lock_count = 0

    for path in root_dir.rglob("*.laab"):
        if path.is_file() or path.is_symlink():
            try:
                path.unlink()
                laab_count += 1
                print(f"Removed: {path}")
            except OSError as error:
                print(f"Failed to remove {path}: {error}")

    for path in root_dir.rglob("*.laab.lock"):
        if path.is_file() or path.is_symlink():
            try:
                path.unlink()
                lock_count += 1
            except OSError as error:
                print(f"Failed to remove {path}: {error}")

    print(
        f"\nRemoved {laab_count} .laab files and "
        f"{lock_count} .laab.lock files."
    )
